name: bedwars_plugin
version: '${project.version}'
main: org.aerial_dad.bedwars_plugin.Bedwars_plugin
api-version: '1.20'
commands:
  bw:
    permission: permission.op
  bedwars:
    permission: permission.op




