name: bedwars_plugin
version: '1.0-SNAPSHOT'
main: org.aerial_dad.bedwars_plugin.Bedwars_plugin
api-version: '1.21'
commands:
  bw:
    permission: permission.op
  bedwars:
    permission: permission.op
  spawnshop:
    usage: /<command>




