name: noodleLegs
version: '${project.version}'
main: org.aerial_dad.noodlelegs.NoodleLegs
commands:
  noodlelegs:
    usage: /<command>
  nl:
    usage: /<command>
  spawnnpc:
    usage: /<command>
  exit:
    usage: /<command>
  shop:
    usage: /<command>
  bw:
    usage: /<command>
  bedwars:
    usage: /<command>
